version: '3'
services:
  weba:
    build: .
    expose:
     - 5000
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"
  nginx:
    image: nginx:alpine
    ports:
     - "8000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - weba

